package com.project.protocol.response;
/**
 * The Response interface defines the contract for all types of responses that
 * can be generated by the server. All classes that implement this interface
 * represent a specific type of response.
 *
 * The Response interface provides a single method, `toString()`, that must be
 * implemented by any class that implements the interface. The `toString()`
 * method should return a string representation of the response.
 */
public interface Response {

    /**
     * Converts the response to a string representation.
     * The specific string representation depends on the type of response.
     *
     * @return a string representation of the response
     */
    String toString();
}

